### ISSUE TITLE
Is PCA coming soon?

### ISSUE THREAD

**Issue by rdvelazquez** [gwaygenomics/pancan_viz#7]
Nice work @gwaygenomics! 
Is there any plan to include dimensionality reduction via PCA as was done [here](https://github.com/cognoma/machine-learning/blob/master/explore/pca-visualization/PCA_Visualization.ipynb)?

**Comment by gwaybio** [comment]
Yeah definitely! See #2 - ideally, I'd like to slowly add new features improved functionality as well

**Comment by rdvelazquez** [comment]
Gotcha. I'll stay tuned for PCA. That will be interesting to see and mess around with as it relates to the current work being done with cognoma. 

Another interesting variable to plot might be how mutated the sample is. You could do total number of mutations, log(mutations) or bin the total number of mutations. I'd offer to help out but I'm not very good with R (yet).

It's interesting how undifferentiated the diseases/organs seem to be with this dimensionality reduction technique compared to PCA. What method of dimensionality reduction is this using?

**Comment by gwaybio** [comment]
> Another interesting variable to plot might be how mutated the sample is. You could do total number of mutations, log(mutations) or bin the total number of mutations. I'd offer to help out but I'm not very good with R (yet).

I agree - mutation burden is a large signal. It would be interesting to visualize here

> It's interesting how undifferentiated the diseases/organs seem to be with this dimensionality reduction technique compared to PCA. What method of dimensionality reduction is this using?

It's a [variational autoencoder](https://arxiv.org/abs/1312.6114). I suspect that part of the reason for the lack of separation is that the algorithm is trained sub-optimally. This was a first pass, I am still tuning some parameters

**Comment by gwaybio** [comment]
@rdvelazquez checkout updates https://gregway.shinyapps.io/pancan_plotter/

Added functionality of `data type` / `algorithm` selection. Still WIP so any suggestions/contributions are welcome! 

Closing this issue since PCA is here (cf8b29913646d2b85c1d1e6dcbe55286bfcedf0c)
